### ISSUE TITLE
Incorrect path to icon image

### ISSUE THREAD

**Issue by ejunker** [thetron/css3buttons_rails_helpers#12]
I created a button using add_button_link_to and the button was there but the icon was not showing. Using the web inspector in Chrome I found that it was trying to load the icon image from http://localhost:3000/stylesheets/css3buttons/gh-icons.png yet that file does not exist at that location.

In the CSS I found that it specifies:

```
background: url(gh-icons.png) 0 99px no-repeat;
```

I had to modify it to use the correct path and filename.

```
background: url(/images/css3buttons/css3-github-buttons-icons.png) 0 99px no-repeat;
```

Sorry I didn't submit a pull request; I'm not very good with Git yet.

**Comment by thetron** [comment]
Thanks ejunker! No worries on the pull request. I'll make sure this all gets fixed as part of our Rails 3.1 asset pipeline updates.
