### ISSUE TITLE
undefined local variable or method `css3buttons_stylesheets' for #<#

### ISSUE THREAD

**Issue by yatesj9** [thetron/css3buttons_rails_helpers#18]
Created a test rails app, with Rails 3, installed the gem and added it to Gemfile, once i add <%= css3buttons_stylesheets %> to my application.html.erb i get this error.

**Comment by yatesj9** [comment]
Wrong place sorry

**Comment by thetron** [comment]
I noticed you also [posted this](https://github.com/michenriksen/css3buttons/issues/39) - you were in the right place the first time :)

What version of the gem are you running? Version 1.0.0+ is **not** backwards compatible with rails 3.0.x - if you need rails 3.0.x support, you need to install version 0.9.5, but placing this in your gemfile:

```
gem 'css3buttons, '0.9.5'
```

and run `bundle update`.

All the instructions for running under rails 3.0.x are in the [readme](https://github.com/thetron/css3buttons_rails_helpers).

**Comment by yatesj9** [comment]
Awesome going to the 0.9.5 worked,also I had to stop/start my websever. Thanks for the help and quick reply
