### ISSUE TITLE
generate wrong asset url when precompile assets

### ISSUE THREAD

**Issue by ayamomiji** [thetron/css3buttons_rails_helpers#20]
rails 3.1.0.rc5

in production mode, when i have:

```
config.action_controller.asset_host = 'http://assets.mydomain.com'
```

it generates:

```
url(css3buttons/icons.png)
```

it should generates:

```
url(http://assets.mydomain.com/assets/css3buttons/icons-md5hash.png)
```

**Comment by ayamomiji** [comment]
this problem was solved in recent commit, and i tried it works well, maybe just need to bump version.

**Comment by thetron** [comment]
Thanks for this - I'm still sorting out a couple of issues on the master branch -- which is why I haven't bumped the version yet on rubygems. I've got an app going into production over the next week, and hopefully will have the last of the asset pipeline stuff sorted by then.
