### ISSUE TITLE
minor_button_group

### ISSUE THREAD

**Issue by hkairi** [thetron/css3buttons_rails_helpers#4]
<%= minor_button_group => true do %>
....
<% end %>

when i try this i do have an error :
compile error
.../app/views/app/index.html.erb:1: syntax error, unexpected tASSOC, expecting kEND
...append=  minor_button_group => true do @output_buffer.safe_c...

**Comment by thetron** [comment]
Thanks hkairi - that was actually a typo in the readme, which has now been updated. It should've been this:

```
<%= minor_button_group do %>
  ...
<% end %>
```
